export const KEYWORDS = [
   'Alexandergv2117',
   'Software Developer',
   'Backend',
   'Frontend',
   'DevOps',
   'React',
   'Next.js',
   'Docker',
   'NestJS',
   'Docker Swarm',
   'Ansible',
   'Microservices',
   'Terrraform',
   'CI/CD',
   'GitHub Actions',
   'Cerbos',
   'Caddy Server',
   'Node.js',
   'TypeORM',
   'PostgreSQL',
   'MongoDB',
   'Nginx',
   'TypeScript',
   'JavaScript',
];
