services:
  STACK_PLACEHOLDER-app:
    image: IMAGE_PLACEHOLDER
    environment:
      - PORT=3000
    networks:
      - caddy
    deploy:
      replicas: 2
      labels:
        caddy: HOST_PLACEHOLDER
        caddy.tls: "/tmp/certs/cert.pem /tmp/certskey.pem"
        caddy.reverse_proxy: "{{upstreams 3000}}"
        caddy.log.output: file /var/log/caddy/HOST_PLACEHOLDER.log
        caddy.log.format: "json"
        caddy.log.level: "INFO"

networks:
  caddy:
    external: true